import { useEffect, useState } from 'react';
import { request } from './api.js';
type RecordItem = { sku: string; revision: number; data: Record<string, unknown> };
type Source = { id: string; sourceId: string; version: number; name: string; contentHash: string };
export function Data({ csrf, onRecord, onWorkflow }: { csrf: string; onRecord: (input: unknown) => void; onWorkflow: (id: string, version: string) => void }) {
  const [records, setRecords] = useState<RecordItem[]>([]); const [sources, setSources] = useState<Source[]>([]);
  const [csv, setCsv] = useState('sku,name,price,material\nDEMO-001,Fictional canvas tote,24,cotton\nDEMO-002,Fictional ceramic cup,,ceramic');
  const [preview, setPreview] = useState<unknown>(null); const [name, setName] = useState('Store listing guidelines'); const [text, setText] = useState('Listing guidelines: use only verified supplier facts. Flag missing price or material. Do not invent dimensions or sustainability claims. Cite the guideline source.'); const [sourceId, setSourceId] = useState('');
  const [query, setQuery] = useState('listing'); const [inspected, setInspected] = useState<unknown>(null); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const load = async () => { const [records, sources] = await Promise.all([request('/records'), request('/knowledge')]); setRecords(records as RecordItem[]); setSources(sources as Source[]); };
  useEffect(() => { void load().catch(error => setError(String(error))); }, []);
  async function action(work: () => Promise<void>) { setBusy(true); setError(''); setMessage(''); try { await work(); } catch (error) { setError(error instanceof Error ? error.message : 'Request failed.'); } finally { setBusy(false); } }
  return <section className="management-panel" aria-label="Records and knowledge"><h2>Records & knowledge</h2><p>Import fictional supplier data, inspect source revisions, and prepare the review workflow. Knowledge retrieval uses local lexical matching.</p>{error && <p role="alert" className="error-message">{error}</p>}{message && <p role="status">{message}</p>}
    <div className="result-grid"><div><h3>CSV records</h3><p>Required headers: sku, name, price. Blank prices are retained as missing information. Up to 500 rows / 250 KB; existing SKUs are never silently overwritten.</p><label>CSV file<input type="file" accept=".csv,text/csv" onChange={event => { const file = event.target.files?.[0]; if (file) void action(async () => { if (file.size > 250000) throw new Error('CSV exceeds 250 KB.'); setCsv(await file.text()); setPreview(null); }); }}/></label><label>CSV contents<textarea rows={6} value={csv} onChange={event => { setCsv(event.target.value); setPreview(null); }}/></label>
      <div className="form-actions"><button className="quiet-button" disabled={busy} onClick={() => { void action(async () => { setPreview(await request('/records/preview', 'POST', { csv }, csrf)); }); }}>Validate CSV</button><button disabled={busy || !preview} onClick={() => { void action(async () => { const result = await request('/records/import', 'POST', { csv }, csrf) as { imported: number }; setMessage(`Imported ${result.imported} records.`); setPreview(null); await load(); }); }}>Import validated records</button></div>{preview !== null && <pre>{JSON.stringify(preview, null, 2)}</pre>}
      <h3>Records ({records.length})</h3>{!records.length ? <p>No records imported yet.</p> : <ul className="data-list">{records.map(record => <li key={record.sku}><strong>{record.sku}</strong> · {String(record.data.name)} · revision {record.revision}<div className="form-actions"><button className="quiet-button" onClick={() => { void action(async () => setInspected(await request(`/records/${encodeURIComponent(record.sku)}`))); }}>Inspect record</button><button className="quiet-button" onClick={() => { onRecord({ record: record.data, revision: record.revision }); setMessage('Record copied to run input below. Select your published catalogue workflow and run it.'); }}>Use record as run input</button></div></li>)}</ul>}
    </div><div><h3>Versioned guidelines</h3><label>Source identity<select value={sourceId} onChange={event => setSourceId(event.target.value)}><option value="">New source</option>{sources.filter((source, index) => sources.findIndex(item => item.sourceId === source.sourceId) === index).map(source => <option key={source.sourceId} value={source.sourceId}>{source.name}</option>)}</select></label><label>Source name<input value={name} onChange={event => setName(event.target.value)}/></label><label>Text or Markdown file<input type="file" accept=".txt,.md,text/plain,text/markdown" onChange={event => { const file = event.target.files?.[0]; if (file) void action(async () => { if (file.size > 100000) throw new Error('Source exceeds 100 KB.'); setText(await file.text()); }); }}/></label><label>Source text<textarea rows={6} value={text} onChange={event => setText(event.target.value)}/></label><button disabled={busy} onClick={() => { void action(async () => { await request('/knowledge', 'POST', { name, text, ...(sourceId ? { sourceId } : {}) }, csrf); await load(); setMessage('Source revision saved and indexed for lexical retrieval. Existing agents keep their pinned revisions.'); }); }}>Save source revision</button>
      <ul className="data-list">{sources.map(source => <li key={source.id}><button className="quiet-button" onClick={() => { void action(async () => setInspected(await request(`/knowledge/${source.id}`))); }}>{source.name} · v{source.version}</button><small>{source.id}</small></li>)}</ul>
      <label>Retrieval test query<input value={query} onChange={event => setQuery(event.target.value)}/></label><button disabled={busy || !sources.length} className="quiet-button" onClick={() => { void action(async () => { const latest = sources.filter((source,index) => sources.findIndex(item => item.sourceId === source.sourceId) === index); setInspected(await request('/knowledge/search', 'POST', { query, versionIds: latest.slice(0,20).map(source => source.id) }, csrf)); }); }}>Search latest source revisions</button>
    </div></div>
    <div className="starter-callout"><h3>Build the catalogue starter</h3><p>Creates a fixture agent pinned to the latest sources and a published workflow: draft → select fields → propose update → review → apply and save artifact.</p><button disabled={busy} onClick={() => { void action(async () => { const result = await request('/catalogue/starter','POST',{},csrf) as { workflow: { id: string }; version: { id: string } }; onWorkflow(result.workflow.id,result.version.id); setMessage('Catalogue starter published. Choose a record above, then run the workflow below.'); }); }}>Create catalogue workflow</button></div>
    {inspected !== null && <details open><summary>Record, source, or retrieval inspection</summary><pre>{JSON.stringify(inspected,null,2)}</pre></details>}
  </section>;
}
