import { useEffect, useState } from 'react';
import type { EvaluationCase } from '@loomrail/contracts';
import { request } from './api.js';
type Case = { id: string; definition: EvaluationCase };
type Report = { id: string; candidateVersionId: string; currentVersionId?: string; passed: boolean; realModelQuality: string; results: { caseId: string; snapshot: EvaluationCase; regression: boolean; candidate: { passed: boolean; assertions: { assertion: unknown; passed: boolean }[] }; current: { passed: boolean } | null }[] };
export function Evaluations({ csrf }: { csrf: string }) {
  const [cases, setCases] = useState<Case[]>([]); const [versions, setVersions] = useState<{id:string;name:string;version:number}[]>([]); const [reports, setReports] = useState<Report[]>([]); const [selected, setSelected] = useState<string[]>([]); const [candidate, setCandidate] = useState(''); const [current, setCurrent] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [caseText, setCaseText] = useState('');
  const load = async () => { const [cases, versions, reports] = await Promise.all([request('/evaluations/cases'),request('/evaluations/versions'),request('/evaluations')]); setCases(cases as Case[]); setVersions(versions as {id:string;name:string;version:number}[]); setReports(reports as Report[]); };
  useEffect(() => { void load().catch(error=>setError(String(error))); }, []);
  async function action(work:()=>Promise<void>) { setBusy(true);setError('');try { await work(); } catch(error) { setError(error instanceof Error ? error.message:'Evaluation failed.'); } finally { setBusy(false); } }
  return <section className="management-panel" aria-label="Evaluations"><h2>Evaluations</h2><p>Compare exact published versions using saved inputs and assertions. All models become fixtures, external actions become isolated record writes, and live records remain untouched. These results measure fixture correctness; semantic model quality still needs human inspection.</p>{error&&<p role="alert" className="error-message">{error}</p>}
    <div className="form-actions"><label>Candidate workflow version<select value={candidate} onChange={event=>setCandidate(event.target.value)}><option value="">Select candidate</option>{versions.map(item=><option key={item.id} value={item.id}>{item.name} · v{item.version} · {item.id.slice(0,8)}</option>)}</select></label><label>Current workflow version<select value={current} onChange={event=>setCurrent(event.target.value)}><option value="">No comparison</option>{versions.map(item=><option key={item.id} value={item.id}>{item.name} · v{item.version} · {item.id.slice(0,8)}</option>)}</select></label></div>
    <button className="quiet-button" disabled={busy} onClick={()=>{void action(async()=>{await request('/evaluations/catalogue-cases','POST',{},csrf);await load();});}}>Add catalogue regression suite</button><p className="small-copy">The built-in suite targets “Catalogue · draft, review, apply”. Other workflows can use custom cases.</p>
    <div className="form-actions"><button className="quiet-button" onClick={()=>setSelected(cases.map(item=>item.id))}>Select all cases</button><button className="quiet-button" onClick={()=>setSelected([])}>Clear selection</button></div>
    <div className="evaluation-cases">{cases.map(item=><label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={event=>setSelected(event.target.checked?[...selected,item.id]:selected.filter(id=>id!==item.id))}/>{item.definition.name}<button className="quiet-button" onClick={()=>setCaseText(JSON.stringify(item.definition,null,2))}>Copy to case editor</button></label>)}</div>
    <button disabled={busy||!candidate||!selected.length} onClick={()=>{void action(async()=>{await request('/evaluations','POST',{candidateVersionId:candidate,...(current?{currentVersionId:current}:{}),caseIds:selected},csrf);await load();});}}>{busy?'Evaluating…':`Run ${selected.length} selected cases`}</button>
    <details><summary>Save a custom case</summary><p>Each save creates a new immutable snapshot for future evaluation reports. Instructions assertions check prompt text, not model understanding.</p><label>Evaluation case JSON<textarea rows={14} value={caseText} onChange={event=>setCaseText(event.target.value)}/></label><button disabled={busy||!caseText} onClick={()=>{void action(async()=>{await request('/evaluations/cases','POST',JSON.parse(caseText),csrf);await load();});}}>Save new case</button></details>
    <h3>Saved comparisons</h3>{!reports.length&&<p>No evaluations yet.</p>}{reports.map(report=><details key={report.id}><summary>{report.passed?'Passed':'Failed'} · {report.results.length} cases · {report.candidateVersionId.slice(0,8)}{report.currentVersionId?` vs ${report.currentVersionId.slice(0,8)}`:''}</summary><p>{report.realModelQuality}</p><table><thead><tr><th>Case</th><th>Candidate</th><th>Current</th><th>Regression</th></tr></thead><tbody>{report.results.map(result=><tr key={result.caseId}><td>{result.snapshot.name}</td><td>{result.candidate.passed?'Pass':'Fail'}</td><td>{result.current?(result.current.passed?'Pass':'Fail'):'—'}</td><td>{result.regression?'Yes':'—'}</td></tr>)}</tbody></table><details><summary>Assertion details and version evidence</summary><pre>{JSON.stringify(report,null,2)}</pre></details></details>)}
  </section>;
}
